import { TintMark, UnderlineMark } from "@/app/app/_components/text-marks";

const processSteps = [
  {
    id: "bifrost",
    title: (
      <>
        Start with <TintMark tone="sky">Bifrost vDOT</TintMark>
      </>
    ),
    copy: (
      <>
        Hold or mint <TintMark tone="sky">vDOT</TintMark> through{" "}
        <UnderlineMark tone="rose">Bifrost</UnderlineMark> before bringing it
        into subvote&apos;s <UnderlineMark tone="amber">VP</UnderlineMark>{" "}
        system.
      </>
    ),
  },
  {
    id: "stake",
    title: (
      <>
        Stake into the <UnderlineMark tone="sage">protocol</UnderlineMark>
      </>
    ),
    copy: (
      <>
        Stake <TintMark tone="sky">vDOT</TintMark> into the subvote staking
        contract. The displayed{" "}
        <UnderlineMark tone="amber">contract address</UnderlineMark> is a
        placeholder for now.
      </>
    ),
  },
  {
    id: "sync",
    title: (
      <>
        Let the <UnderlineMark tone="sage">backend sync</UnderlineMark>
      </>
    ),
    copy: (
      <>
        A backend worker watches the stake state, updates your staked amount,
        and recalculates <TintMark tone="amber">VP_max</TintMark>.
      </>
    ),
  },
  {
    id: "use-vp",
    title: (
      <>
        Use <TintMark tone="amber">VP</TintMark> inside the app
      </>
    ),
    copy: (
      <>
        Spend <TintMark tone="amber">VP</TintMark> to join discussions, post
        messages, and lock capacity when you open a topic.
      </>
    ),
  },
] as const;

const trustNotes = [
  {
    id: "yield",
    content: (
      <>
        Your <TintMark tone="sky">vDOT</TintMark> position keeps its own{" "}
        <UnderlineMark tone="sage">yield</UnderlineMark>. subvote does not skim
        or redirect that yield.
      </>
    ),
  },
  {
    id: "internal-balance",
    content: (
      <>
        <TintMark tone="amber">VP</TintMark> is an internal platform-side
        balance. It is <UnderlineMark tone="rose">not a token</UnderlineMark>{" "}
        and it is not transferable.
      </>
    ),
  },
  {
    id: "no-fee",
    content: (
      <>
        The platform takes <UnderlineMark tone="rose">no fee</UnderlineMark>{" "}
        from the staking yield itself.
      </>
    ),
  },
] as const;

const vpUses = [
  {
    id: "join",
    title: (
      <>
        Join a <UnderlineMark tone="sky">topic</UnderlineMark>
      </>
    ),
    copy: (
      <>
        Use available <TintMark tone="amber">VP</TintMark> to enter an active
        room and participate in the discussion.
      </>
    ),
  },
  {
    id: "message",
    title: (
      <>
        Send <UnderlineMark tone="sage">messages</UnderlineMark>
      </>
    ),
    copy: (
      <>
        Each message spends <TintMark tone="amber">VP</TintMark> according to
        topic type and message length.
      </>
    ),
  },
  {
    id: "start",
    title: (
      <>
        Start a <UnderlineMark tone="rose">topic</UnderlineMark>
      </>
    ),
    copy: (
      <>
        Opening a topic locks <TintMark tone="rose">50 VP</TintMark> until the
        topic is closed and archived.
      </>
    ),
  },
] as const;

const formulaExamples = [
  { stake: "1,000 vDOT", vp: "1,000 VP" },
  { stake: "4,000 vDOT", vp: "2,000 VP" },
  { stake: "9,000 vDOT", vp: "3,000 VP" },
] as const;

export function GetVpDetails() {
  return (
    <div className="mx-auto flex min-h-full w-full max-w-none flex-col gap-4 px-0 pb-8 sm:gap-5">
      <header className="grid gap-6 xl:grid-cols-[minmax(0,1fr)_26rem] xl:items-start">
        <section className="px-1 pt-1 sm:px-2">
          <h1 className="max-w-[11ch] text-[clamp(3.3rem,7vw,6.6rem)] font-normal leading-[0.88] tracking-[-0.09em] text-neutral-950">
            Stake <TintMark tone="sky">Bifrost vDOT</TintMark> and receive
            usable <UnderlineMark tone="amber">VP</UnderlineMark>.
          </h1>
          <p className="mt-5 max-w-4xl text-[1rem] leading-7 text-neutral-600 sm:text-[1.08rem]">
            subvote uses <TintMark tone="sky">Bifrost vDOT</TintMark> as the
            staking asset behind discussion power. Stake{" "}
            <TintMark tone="sky">vDOT</TintMark> into the protocol, keep the{" "}
            <UnderlineMark tone="sage">yield</UnderlineMark> generated by the
            position, and receive <TintMark tone="amber">VP</TintMark> as an
            internal balance for participation inside the app.
          </p>

          <div className="mt-8 grid gap-3 sm:grid-cols-3 xl:max-w-4xl">
            <HighlightPill
              title="Yield stays with vDOT"
              copy="The staking position keeps producing its own yield."
            />
            <HighlightPill
              title="No platform fee"
              copy="subvote does not take a cut from that yield."
            />
            <HighlightPill
              title="VP is app-side"
              copy="VP is backend-synced participation power, not a token."
            />
          </div>
        </section>

        <aside className="rounded-[1.9rem] border border-neutral-950 bg-neutral-950 p-5 text-white shadow-[0_22px_50px_rgba(15,17,17,0.16)] sm:p-6">
          <p className="text-[0.68rem] font-medium uppercase tracking-[0.22em] text-white/55">
            VP formula
          </p>
          <div className="mt-5 rounded-[1.45rem] border border-white/10 bg-white/5 px-5 py-5">
            <FormulaDisplay />
          </div>
          <p className="text-white/78 mt-4 text-sm leading-6">
            <TintMark tone="amber" inverse>
              VP
            </TintMark>{" "}
            rises with your stake, but{" "}
            <UnderlineMark tone="rose" inverse>
              not linearly
            </UnderlineMark>
            . Larger positions gain more capacity while the curve stays
            controlled.
          </p>

          <dl className="mt-6 grid gap-3">
            <MetaRow
              label="Staking contract"
              value="0x0000...0000"
              mono
              helper="placeholder"
            />
            <MetaRow label="Staking asset" value="Bifrost vDOT" />
            <MetaRow label="VP settlement" value="Backend-synced only" />
          </dl>
        </aside>
      </header>

      <section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(18rem,0.88fr)]">
        <article className="border-black/8 rounded-[1.8rem] border bg-[rgba(255,255,255,0.74)] p-5 shadow-[inset_0_1px_0_rgba(255,255,255,0.72)] sm:p-6">
          <p className="text-[0.68rem] font-medium uppercase tracking-[0.22em] text-neutral-500">
            How it works
          </p>
          <ol className="mt-5 grid gap-3">
            {processSteps.map((step, index) => (
              <li
                key={step.id}
                className="border-black/8 rounded-[1.35rem] border bg-[rgba(247,243,236,0.82)] px-4 py-4"
              >
                <div className="flex gap-3">
                  <span className="border-black/8 mt-0.5 flex size-7 shrink-0 items-center justify-center rounded-full border bg-white text-[0.75rem] font-semibold text-neutral-700">
                    {index + 1}
                  </span>
                  <div>
                    <h2 className="text-base font-semibold leading-6 tracking-[-0.03em] text-neutral-950">
                      {step.title}
                    </h2>
                    <p className="mt-1.5 max-w-[42rem] text-sm leading-6 text-neutral-600">
                      {step.copy}
                    </p>
                  </div>
                </div>
              </li>
            ))}
          </ol>
        </article>

        <article className="border-black/8 rounded-[1.8rem] border bg-[rgba(255,255,255,0.72)] p-5 shadow-[inset_0_1px_0_rgba(255,255,255,0.72)] sm:p-6">
          <p className="text-[0.68rem] font-medium uppercase tracking-[0.22em] text-neutral-500">
            What stays true
          </p>
          <div className="mt-5 grid gap-3">
            {trustNotes.map((note) => (
              <div
                key={note.id}
                className="border-black/8 rounded-[1.3rem] border bg-[rgba(247,243,236,0.82)] px-4 py-4"
              >
                <p className="text-sm leading-6 text-neutral-700">
                  {note.content}
                </p>
              </div>
            ))}
          </div>
        </article>
      </section>

      <section className="grid gap-4 lg:grid-cols-[minmax(0,1fr)_minmax(18rem,0.78fr)]">
        <article className="border-black/8 rounded-[1.8rem] border bg-[rgba(255,255,255,0.74)] p-5 shadow-[inset_0_1px_0_rgba(255,255,255,0.72)] sm:p-6">
          <p className="text-[0.68rem] font-medium uppercase tracking-[0.22em] text-neutral-500">
            What VP is for
          </p>
          <div className="mt-5 grid gap-3 md:grid-cols-3">
            {vpUses.map((item) => (
              <div
                key={item.id}
                className="border-black/8 rounded-[1.35rem] border bg-[rgba(247,243,236,0.82)] px-4 py-4"
              >
                <h2 className="text-base font-semibold leading-6 tracking-[-0.03em] text-neutral-950">
                  {item.title}
                </h2>
                <p className="mt-2 text-sm leading-6 text-neutral-600">
                  {item.copy}
                </p>
              </div>
            ))}
          </div>
        </article>

        <article className="border-black/8 rounded-[1.8rem] border bg-[rgba(255,255,255,0.72)] p-5 shadow-[inset_0_1px_0_rgba(255,255,255,0.72)] sm:p-6">
          <p className="text-[0.68rem] font-medium uppercase tracking-[0.22em] text-neutral-500">
            Reading the curve
          </p>
          <div className="mt-5 grid gap-3">
            {formulaExamples.map((example) => (
              <div
                key={example.stake}
                className="border-black/8 flex items-center justify-between rounded-[1.2rem] border bg-[rgba(247,243,236,0.82)] px-4 py-3"
              >
                <span className="text-sm leading-6 text-neutral-600">
                  {example.stake}
                </span>
                <span className="text-sm font-semibold leading-6 text-neutral-950">
                  {example.vp}
                </span>
              </div>
            ))}
          </div>
          <p className="mt-4 text-sm leading-6 text-neutral-600">
            The formula uses the human-readable{" "}
            <TintMark tone="sky">vDOT</TintMark> amount, not the chain&apos;s
            smallest unit.
          </p>
        </article>
      </section>

      <article className="border-black/8 rounded-[1.8rem] border bg-[rgba(255,255,255,0.72)] p-5 shadow-[inset_0_1px_0_rgba(255,255,255,0.72)] sm:p-6">
        <p className="text-[0.68rem] font-medium uppercase tracking-[0.22em] text-neutral-500">
          Transparency note
        </p>
        <p className="mt-3 max-w-[64rem] text-sm leading-6 text-neutral-600 sm:text-[0.98rem]">
          This page explains the economic relationship only:{" "}
          <TintMark tone="sky">Bifrost vDOT</TintMark> is the capital base,{" "}
          <TintMark tone="amber">VP</TintMark> is the app-side participation
          balance, and the platform keeps the conversion logic visible. Wallet
          connection, staking actions, and VP ledger views can sit under this
          layer later.
        </p>
      </article>
    </div>
  );
}

function HighlightPill({ copy, title }: { copy: string; title: string }) {
  return (
    <div className="border-black/8 rounded-[1.35rem] border bg-[rgba(247,243,236,0.84)] px-4 py-4">
      <p className="text-[0.7rem] font-medium uppercase tracking-[0.18em] text-neutral-500">
        {title}
      </p>
      <p className="mt-2 text-sm leading-6 text-neutral-700">{copy}</p>
    </div>
  );
}

function MetaRow({
  helper,
  label,
  mono = false,
  value,
}: {
  helper?: string;
  label: string;
  mono?: boolean;
  value: string;
}) {
  return (
    <div className="rounded-[1.2rem] border border-white/10 bg-white/5 px-4 py-3">
      <p className="text-[0.68rem] font-medium uppercase tracking-[0.18em] text-white/45">
        {label}
      </p>
      <div className="mt-2 flex items-center gap-2">
        <p
          className={`text-sm leading-6 text-white ${
            mono ? "font-mono tracking-[-0.02em]" : "font-medium"
          }`}
        >
          {value}
        </p>
        {helper ? (
          <span className="bg-white/6 rounded-full border border-white/10 px-2 py-0.5 text-[0.62rem] font-medium uppercase tracking-[0.14em] text-white/45">
            {helper}
          </span>
        ) : null}
      </div>
    </div>
  );
}

function FormulaDisplay() {
  return (
    <div
      className="flex justify-center pb-1"
      aria-label="VP max equals the floor of one thousand times the square root of vDOT staked divided by one thousand"
    >
      <div className="flex max-w-full items-center justify-center gap-1.5 whitespace-nowrap text-white sm:gap-2">
        <div className="flex shrink-0 items-end gap-1 leading-none tracking-[-0.06em]">
          <span className="font-serif text-[1.55rem] sm:text-[2rem]">VP</span>
          <span className="mb-[0.18rem] text-[0.74rem] sm:text-[0.92rem]">
            max
          </span>
          <span className="mb-[0.12rem] ml-1 text-[1.24rem] sm:text-[1.55rem]">
            =
          </span>
        </div>

        <div className="flex shrink-0 items-center gap-2 sm:gap-2.5">
          <span
            aria-hidden="true"
            className="h-12 w-[0.56rem] shrink-0 rounded-bl-[0.08rem] border-b-[0.13rem] border-l-[0.13rem] border-white/90 sm:h-[3.6rem] sm:w-[0.7rem] sm:border-b-[0.16rem] sm:border-l-[0.16rem]"
          />

          <div className="flex shrink-0 items-center gap-1.5 sm:gap-2">
            <span className="text-[0.88rem] leading-none tracking-[-0.05em] sm:text-[1.18rem]">
              1000
            </span>
            <span
              aria-hidden="true"
              className="text-white/82 text-[1.02rem] leading-none sm:text-[1.32rem]"
            >
              ×
            </span>

            <div className="flex items-start gap-0.5 sm:gap-1">
              <span
                aria-hidden="true"
                className="mt-[0.08rem] text-[2rem] font-light leading-[0.8] text-white/95 sm:text-[2.6rem]"
              >
                √
              </span>

              <div className="flex min-w-[5rem] flex-col items-center pt-0.5 sm:min-w-[6.3rem]">
                <span className="px-1 font-serif text-[0.8rem] leading-none tracking-[-0.045em] sm:text-[1.08rem]">
                  vDOT
                  <span className="ml-1 align-[-0.36em] text-[0.62em] tracking-[-0.03em]">
                    staked
                  </span>
                </span>
                <span
                  aria-hidden="true"
                  className="bg-white/88 mt-0.5 h-px w-full"
                />
                <span className="pt-0.5 text-[0.78rem] leading-none tracking-[-0.04em] sm:text-[0.98rem]">
                  1000
                </span>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
